---
- name: Find all .app bundles in /Applications
  ansible.builtin.find:
    paths: /Applications
    patterns: "*.app"
    file_type: directory
    recurse: no
  register: apps

- name: Check for com.apple.quarantine attribute
  ansible.builtin.command:
    cmd: xattr -p com.apple.quarantine {{ item.path }}
  register: quarantine_check
  loop: "{{ apps.files }}"
  ignore_errors: true

- name: Show applications with quarantine attribute
  ansible.builtin.debug:
    msg: "{{ item.item.path }} is quarantined ({{ item.stdout }})"
  loop: "{{ quarantine_check.results }}"
  when: item.rc == 0